FROM eclipse-temurin:17

LABEL mentainer="*"

WORKDIR /app

COPY target/springboot-restful-webservices-v2-0.0.1-SNAPSHOT.jar /app/springboot-restful-webservices-v2.jar

ENTRYPOINT ["java", "-jar", "springboot-restful-webservices-v2.jar"]